### ISSUE TITLE
Use asset-tools to obtain appropriate binary files

### ISSUE THREAD

**Issue by eflumerf** [philiprodrigues/integrationtest#29]
The --frame-file argument has served us well, but it may be time to make the automation slightly smarter and use the asset manager to get the appropriate binary file for a given readout app (potentially even allowing multiple different types of fake readout within a single integration test!)

**Comment by plasorak** [comment]
Actually, I think this is a daqconf (or even readout) issue. It should be that daqconf gives the asset id to the emulator module and it goes and fetches it.

**Comment by plasorak** [comment]
I said readout, but the emulator module may be somewhere else...

**Comment by bieryAtFnal** [comment]
Interesting idea...
However, I think that we should be careful not to lock ourselves into a model in which we can only use files from the asset system.
That might imply a prefix like "asset://" vs. "file://" or something like that, if we decide to add functionality to the emulator code.  

We should talk with the developers/managers of the emulator module(s).  I can imagine that a case could/might be made to follow a model of having the emulator module do a small/reasonable of things well instead of asking it do many things.  And, that might imply giving it a location of a file that is locally accessible, rather than asking it to fetch files.  Of course, the fetching of files could be encapsulated in a utility class or method, and the emulator module could simply invoke that code.

From my side, my sense is that file handling is easier in Python than C++, so I'd vote for keeping the emulator modules as they are.

**Comment by plasorak** [comment]
> That might imply a prefix like "asset://" vs. "file://" or something like that, if we decide to add functionality to the emulator code.

I agree.

> From my side, my sense is that file handling is easier in Python than C++, so I'd vote for keeping the emulator modules as they are.

I could be convinced to do that. But in this case, I'd prefer to have the asset path resolution in daqconf.

**Comment by eflumerf** [comment]
Superseded by https://github.com/DUNE-DAQ/daqconf/pull/290
